import { Course, Note, Assignment, Quiz, Assessment, QuestionBankItem, Student, Payment, Certificate } from './types';

export const INITIAL_COURSES: Course[] = [
  {
    id: 1,
    title: 'Full-Stack Modern Web Engineering',
    instructor: 'Dr. Sarah Malik',
    instructorRole: 'Lead Architect @ CloudScale, Ex-Google',
    instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    category: 'Development',
    level: 'Advanced',
    duration: '8 weeks (48h total)',
    lessonsCount: 36,
    price: 4999,
    originalPrice: 6999,
    rating: 4.9,
    reviewsCount: 312,
    students: 1240,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=900&q=80',
    description: 'Master industry-ready React 19, Next.js App Router, TypeScript, PostgreSQL, Docker, and CI/CD pipelines through end-to-end architecture.',
    purchased: true,
    progress: 72,
    badge: 'Bestseller',
    whatYouWillLearn: [
      'Design modular frontends with modern React, Hooks, and State Management',
      'Build secure REST & GraphQL microservices with Node.js and PostgreSQL',
      'Deploy resilient containerized web apps on cloud infrastructure with Docker',
      'Implement real-time features using WebSockets and optimize Core Web Vitals',
    ],
    requirements: [
      'Basic knowledge of HTML, CSS and foundational JavaScript syntax',
      'Code editor installed (VS Code recommended)',
    ],
    modules: [
      {
        id: 101,
        title: 'Module 1: Modern Frontend Foundations & Architecture',
        duration: '10h 30m',
        lessons: [
          { id: 1001, title: 'Component Design Patterns & Clean Code', duration: '45m', type: 'video', completed: true },
          { id: 1002, title: 'Deep Dive into React 19 Hooks & Concurrency', duration: '55m', type: 'video', completed: true },
          { id: 1003, title: 'State Management at Enterprise Scale', duration: '40m', type: 'video', completed: true },
          { id: 1004, title: 'Lesson 1 Summary Notes & Reference Code', duration: '15m', type: 'article', completed: true },
        ],
      },
      {
        id: 102,
        title: 'Module 2: Server-Side Systems & PostgreSQL',
        duration: '14h 15m',
        lessons: [
          { id: 1005, title: 'Database Design & Relational Modeling', duration: '60m', type: 'video', completed: true },
          { id: 1006, title: 'Authentication, JWT & RBAC Patterns', duration: '50m', type: 'video', completed: true },
          { id: 1007, title: 'RESTful API Security & Rate Limiting', duration: '45m', type: 'video', completed: false },
          { id: 1008, title: 'Mid-Module Quiz: Backend Concepts', duration: '20m', type: 'quiz', completed: false },
        ],
      },
      {
        id: 103,
        title: 'Module 3: Cloud Deployment, Docker & Final Assessment',
        duration: '12h 00m',
        lessons: [
          { id: 1009, title: 'Containerizing Applications with Docker', duration: '55m', type: 'video', completed: false },
          { id: 1010, title: 'CI/CD Pipelines with GitHub Actions', duration: '45m', type: 'video', completed: false },
          { id: 1011, title: 'Capstone Project Guidelines & Evaluation', duration: '30m', type: 'resource', completed: false },
        ],
      },
    ],
  },
  {
    id: 2,
    title: 'Applied AI & Python Data Analytics',
    instructor: 'Aman Verma',
    instructorRole: 'Principal Data Scientist @ QuantAI',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    category: 'Data & AI',
    level: 'Intermediate',
    duration: '6 weeks (36h total)',
    lessonsCount: 28,
    price: 3999,
    originalPrice: 5499,
    rating: 4.8,
    reviewsCount: 245,
    students: 980,
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
    description: 'Harness Python, Pandas, NumPy, statistical modeling, and LLM integrations to turn complex data into actionable dashboards and AI features.',
    purchased: true,
    progress: 58,
    badge: 'Popular',
    whatYouWillLearn: [
      'Wrangle messy tabular datasets using Pandas and NumPy',
      'Build predictive regression & classification pipelines with Scikit-learn',
      'Construct automated executive analytics dashboards with Streamlit',
      'Integrate generative AI APIs for real-time text analysis and automation',
    ],
    requirements: ['High school math fundamentals', 'Any programming background is helpful'],
    modules: [
      {
        id: 201,
        title: 'Module 1: Advanced Data Manipulation',
        duration: '8h 20m',
        lessons: [
          { id: 2001, title: 'Pandas Vectorization Techniques', duration: '45m', type: 'video', completed: true },
          { id: 2002, title: 'Exploratory Data Analysis Mastery', duration: '50m', type: 'video', completed: true },
        ],
      },
    ],
  },
  {
    id: 3,
    title: 'UI/UX Design Systems & Product Strategy',
    instructor: 'Nisha Rao',
    instructorRole: 'Staff Product Designer @ FinDesign',
    instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    category: 'Design',
    level: 'Beginner',
    duration: '5 weeks (30h total)',
    lessonsCount: 24,
    price: 3499,
    originalPrice: 4599,
    rating: 4.9,
    reviewsCount: 410,
    students: 1540,
    image: 'https://images.unsplash.com/photo-1581291518655-9523c932dede?auto=format&fit=crop&w=900&q=80',
    description: 'Learn modern Figma component architecture, design tokens, micro-interactions, responsive grids, and design sprint methodologies.',
    purchased: true,
    progress: 64,
    badge: 'Top Rated',
    whatYouWillLearn: [
      'Create scalable multi-brand design systems with Figma variables and auto-layout',
      'Conduct user interviews, heuristic audits, and synthesize actionable user personas',
      'Prototype complex micro-interactions with high-fidelity transitions',
      'Deliver developer-ready tokenized design specifications',
    ],
    requirements: ['Free Figma account', 'No prior design experience necessary'],
    modules: [
      {
        id: 301,
        title: 'Module 1: Design Foundations & Typography',
        duration: '6h 00m',
        lessons: [
          { id: 3001, title: 'Visual Hierarchy & Grid Systems', duration: '40m', type: 'video', completed: true },
          { id: 3002, title: 'Building Adaptive Components in Figma', duration: '60m', type: 'video', completed: true },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'Data Structures, Algorithms & System Design',
    instructor: 'Ritika Joshi',
    instructorRole: 'Principal Engineer @ MetaTech',
    instructorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    category: 'Programming',
    level: 'Advanced',
    duration: '10 weeks (60h total)',
    lessonsCount: 48,
    price: 4299,
    originalPrice: 5899,
    rating: 4.8,
    reviewsCount: 180,
    students: 760,
    image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80',
    description: 'Conquer complex algorithmic challenges, dynamic programming, graph theory, distributed caching, and large-scale system design interviews.',
    purchased: false,
    badge: 'Recommended',
    whatYouWillLearn: [
      'Solve FAANG-level algorithmic challenges with optimal time/space complexity',
      'Master Graphs, Trees, Heaps, and Dynamic Programming with pattern recognition',
      'Design distributed systems with high availability, sharding, and caching layers',
    ],
    requirements: ['Comfortable coding in Python, Java, C++, or TypeScript'],
    modules: [],
  },
  {
    id: 5,
    title: 'Cloud Architecture & Kubernetes Orchestration',
    instructor: 'Vikram Shah',
    instructorRole: 'Cloud Solutions Architect @ AWS Partner',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    category: 'Cloud & DevOps',
    level: 'Intermediate',
    duration: '7 weeks (42h total)',
    lessonsCount: 32,
    price: 4499,
    originalPrice: 6099,
    rating: 4.7,
    reviewsCount: 140,
    students: 620,
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=900&q=80',
    description: 'Architect multi-region cloud infrastructures, automated Terraform provisioning, Kubernetes cluster scaling, and serverless microservices.',
    purchased: false,
    whatYouWillLearn: [
      'Deploy containerized applications to production Kubernetes clusters',
      'Automate cloud infrastructure provisioning using Terraform IaC',
      'Configure VPCs, IAM roles, security groups, and automated backups',
    ],
    requirements: ['Basic Linux command line knowledge'],
    modules: [],
  },
  {
    id: 6,
    title: 'Growth Marketing & Analytics Strategy',
    instructor: 'Mira Sen',
    instructorRole: 'Head of Growth @ SaaSify',
    instructorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    category: 'Marketing',
    level: 'Beginner',
    duration: '4 weeks (24h total)',
    lessonsCount: 20,
    price: 2999,
    originalPrice: 3999,
    rating: 4.6,
    reviewsCount: 195,
    students: 890,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80',
    description: 'Learn data-driven user acquisition, conversion rate optimization, CAC/LTV funnels, SEO engineering, and paid performance marketing.',
    purchased: false,
    whatYouWillLearn: [
      'Build conversion funnels with tracking and attribution analytics',
      'Run rigorous A/B experiments on landing pages and onboarding flows',
      'Scale organic traffic with modern technical SEO frameworks',
    ],
    requirements: ['No prior marketing experience required'],
    modules: [],
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 1,
    title: 'Module 3: React Hooks & Concurrency Cheatsheet',
    course: 'Full-Stack Modern Web Engineering',
    module: 'React Fundamentals',
    date: 'Aug 22, 2026',
    type: 'PDF',
    size: '2.4 MB',
    contentPreview: 'Comprehensive reference covering useTransition, useDeferredValue, custom hook memorization patterns, and clean architecture examples.',
  },
  {
    id: 2,
    title: 'PostgreSQL Relational Schema & Indexing Guide',
    course: 'Full-Stack Modern Web Engineering',
    module: 'Database Design',
    date: 'Aug 19, 2026',
    type: 'PDF',
    size: '1.8 MB',
    contentPreview: 'In-depth notes on B-Tree vs GIN indexes, foreign key constraints, connection pooling, and optimizing query execution plans.',
  },
  {
    id: 3,
    title: 'Design Tokens & Figma Auto-Layout Spec',
    course: 'UI/UX Design Systems & Product Strategy',
    module: 'Design Tokens',
    date: 'Aug 16, 2026',
    type: 'DOC',
    size: '950 KB',
    contentPreview: 'Standardized color palette, typographic hierarchy, responsive grid scale, and dark mode contrast specifications.',
  },
  {
    id: 4,
    title: 'Python Pandas Vectorized Operations Reference',
    course: 'Applied AI & Python Data Analytics',
    module: 'Data Wrangling',
    date: 'Aug 12, 2026',
    type: 'PDF',
    size: '3.1 MB',
    contentPreview: 'Fast data transforms using numpy ufuncs, groupby aggregations, window functions, and memory optimization tricks.',
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 1,
    title: 'Build Secure Authentication & JWT Flow',
    course: 'Full-Stack Modern Web Engineering',
    due: 'Aug 29, 2026',
    status: 'Pending',
    maxScore: 100,
    instructions: 'Implement an end-to-end authentication module featuring HTTP-only cookies, password hashing with Argon2, and protected route middleware.',
  },
  {
    id: 2,
    title: 'Create Reusable UI Component Library in Figma',
    course: 'UI/UX Design Systems & Product Strategy',
    due: 'Aug 26, 2026',
    status: 'Submitted',
    score: 92,
    maxScore: 100,
    submittedFile: 'figma_component_system_v2.fig',
    submissionDate: 'Aug 24, 2026',
    feedback: 'Excellent use of Auto-Layout and semantic token variants! Minor adjustment needed for contrast in secondary dark state.',
  },
  {
    id: 3,
    title: 'Exploratory Data Analysis on Customer Churn',
    course: 'Applied AI & Python Data Analytics',
    due: 'Aug 20, 2026',
    status: 'Graded',
    score: 95,
    maxScore: 100,
    submittedFile: 'churn_analysis_final.ipynb',
    submissionDate: 'Aug 19, 2026',
    feedback: 'Outstanding visualizations and thoughtful feature engineering recommendations.',
  },
  {
    id: 4,
    title: 'Docker Multi-Stage Build & Container Pipeline',
    course: 'Full-Stack Modern Web Engineering',
    due: 'Aug 15, 2026',
    status: 'Overdue',
    maxScore: 100,
    instructions: 'Construct a minimal, secure Dockerfile utilizing Alpine Linux multi-stage compilation to reduce image footprint under 80MB.',
  },
];

export const INITIAL_QUIZZES: Quiz[] = [
  {
    id: 1,
    title: 'React Core Architecture & Hooks',
    course: 'Full-Stack Modern Web Engineering',
    duration: '15 mins',
    durationMinutes: 15,
    questionsCount: 4,
    score: 85,
    status: 'Completed',
    questions: [
      {
        id: 1,
        question: 'What is the primary benefit of React’s Virtual DOM reconciliation process?',
        options: [
          'It replaces the need for a web browser engine',
          'It minimizes direct DOM manipulations by batching and computing minimal diffs',
          'It compiles JavaScript into native C++ binaries',
          'It guarantees zero-memory usage in the browser',
        ],
        correctAnswer: 1,
        explanation: 'React’s Virtual DOM compares virtual trees in memory to calculate the most efficient batch of real DOM mutations.',
      },
      {
        id: 2,
        question: 'Which Hook should you use to execute side-effects after the component renders?',
        options: ['useMemo', 'useState', 'useEffect', 'useCallback'],
        correctAnswer: 2,
        explanation: 'useEffect is specifically designated for subscriptions, API calls, timers, and external system sync.',
      },
      {
        id: 3,
        question: 'What is the key rule when defining React Hooks?',
        options: [
          'Hooks must be called inside loops and conditional blocks',
          'Hooks must only be called at the top level of React functions',
          'Hooks must only be written in class components',
          'Hooks cannot accept parameters',
        ],
        correctAnswer: 1,
        explanation: 'Hooks must always be invoked in the same order on every render, at the top level of functional components.',
      },
      {
        id: 4,
        question: 'Which CSS layout model provides two-dimensional alignment along rows and columns?',
        options: ['CSS Flexbox', 'CSS Grid', 'Float positioning', 'Absolute tables'],
        correctAnswer: 1,
        explanation: 'CSS Grid is designed for 2D layouts (rows and columns simultaneously), whereas Flexbox is 1D.',
      },
    ],
  },
  {
    id: 2,
    title: 'Python Pandas & Data Manipulation',
    course: 'Applied AI & Python Data Analytics',
    duration: '20 mins',
    durationMinutes: 20,
    questionsCount: 4,
    status: 'Available',
    questions: [
      {
        id: 1,
        question: 'Which Pandas method is best for computing summary statistics across numerical columns?',
        options: ['df.summary()', 'df.describe()', 'df.stats()', 'df.aggregate()'],
        correctAnswer: 1,
        explanation: 'df.describe() generates count, mean, std, min, percentiles, and max.',
      },
      {
        id: 2,
        question: 'What is the fundamental difference between a Pandas Series and a DataFrame?',
        options: [
          'A Series is 1-dimensional while a DataFrame is a 2-dimensional tabular structure',
          'A Series holds only strings while a DataFrame holds only numbers',
          'DataFrames cannot be indexed',
          'Series cannot be converted to lists',
        ],
        correctAnswer: 0,
        explanation: 'A Series is a one-dimensional labeled array, and a DataFrame is a two-dimensional labeled data structure.',
      },
      {
        id: 3,
        question: 'How do you handle missing NaN values by replacing them with the column median?',
        options: [
          'df.drop_na()',
          'df.fillna(df.median())',
          'df.replace_null()',
          'df.remove_missing()',
        ],
        correctAnswer: 1,
        explanation: 'df.fillna() substitutes missing values with the computed median or specified values.',
      },
      {
        id: 4,
        question: 'Which join type returns all rows from both tables, filling missing matches with NaN?',
        options: ['Inner Join', 'Left Join', 'Outer Join', 'Cross Join'],
        correctAnswer: 2,
        explanation: 'An outer join retains all rows from both datasets, placing NaN where records do not align.',
      },
    ],
  },
  {
    id: 3,
    title: 'Design Systems & Token Architecture',
    course: 'UI/UX Design Systems & Product Strategy',
    duration: '12 mins',
    durationMinutes: 12,
    questionsCount: 3,
    status: 'Available',
    questions: [
      {
        id: 1,
        question: 'What is a "Design Token"?',
        options: [
          'A cryptographic blockchain currency used to buy icons',
          'A semantic key-value pair representing a design decision (color, spacing, font) across platforms',
          'A physical badge awarded to UX researchers',
          'A Figma plugin for generating wireframes',
        ],
        correctAnswer: 1,
        explanation: 'Design tokens are platform-agnostic design variables that sync between design tools and codebases.',
      },
      {
        id: 2,
        question: 'According to WCAG 2.1 AA standards, what is the minimum contrast ratio for normal body text?',
        options: ['3:1', '4.5:1', '7:1', '2:1'],
        correctAnswer: 1,
        explanation: 'WCAG 2.1 AA requires at least 4.5:1 contrast for normal body text and 3:1 for large text.',
      },
      {
        id: 3,
        question: 'In Figma, what feature dynamically resizes card containers when nested contents change?',
        options: ['Auto-Layout', 'Vector Boolean', 'Smart Animate', 'Component Variant'],
        correctAnswer: 0,
        explanation: 'Auto-Layout automatically adjusts container dimensions, padding, and gaps based on child items.',
      },
    ],
  },
];

export const INITIAL_ASSESSMENTS: Assessment[] = [
  {
    id: 1,
    title: 'Frontend Engineering Capstone Assessment',
    course: 'Full-Stack Modern Web Engineering',
    duration: '60 mins',
    durationMinutes: 60,
    questionsCount: 10,
    status: 'Available',
    proctored: true,
    passingScore: 75,
    attemptsAllowed: 2,
    attemptsTaken: 0,
    instructions: [
      'Ensure you are seated in a well-lit, quiet room.',
      'Webcam and microphone must remain connected and active throughout the entire session.',
      'Full-screen mode will be locked upon starting. Switching tabs or windows triggers an automatic proctoring flag.',
      'Calculators, secondary monitors, or unauthorized browser extensions are strictly prohibited.',
      'The assessment will automatically submit when the 60-minute countdown reaches 00:00.',
    ],
    questions: [
      {
        id: 1,
        question: 'Which HTTP method should be idempotent and used to completely replace an existing resource?',
        options: ['POST', 'PUT', 'PATCH', 'CONNECT'],
        correctAnswer: 1,
        explanation: 'PUT is designed to be idempotent and replaces the entire target resource with the provided payload.',
      },
      {
        id: 2,
        question: 'What is the primary advantage of HTTP/2 over HTTP/1.1 in web performance?',
        options: [
          'It replaces TCP with UDP entirely',
          'It supports multiplexing multiple requests over a single TCP connection',
          'It requires unencrypted plain text transfers',
          'It removes the need for web servers',
        ],
        correctAnswer: 1,
        explanation: 'HTTP/2 multiplexing allows concurrent request and response messages over one connection, eliminating head-of-line blocking.',
      },
      {
        id: 3,
        question: 'In React, what will happen if state is mutated directly without calling the setter function?',
        options: [
          'The application throws an immediate compile error',
          'React will not detect the change and will not schedule a re-render',
          'The browser refreshes automatically',
          'The state rolls back to initial values',
        ],
        correctAnswer: 1,
        explanation: 'React compares state references by identity; direct mutation skips triggering scheduled reconciliation renders.',
      },
      {
        id: 4,
        question: 'Which SQL clause is used to filter records after an aggregate GROUP BY operation?',
        options: ['WHERE', 'HAVING', 'FILTER', 'LIMIT'],
        correctAnswer: 1,
        explanation: 'HAVING filters aggregated groups, whereas WHERE filters individual rows before grouping.',
      },
      {
        id: 5,
        question: 'What does the CSS "content-visibility: auto" property optimize?',
        options: [
          'Screen reader accessibility',
          'Rendering performance by skipping off-screen element layout and painting',
          'Automatic translation of text',
          'Image compression quality',
        ],
        correctAnswer: 1,
        explanation: 'content-visibility: auto allows the browser to defer rendering work for elements currently outside the viewport.',
      },
      {
        id: 6,
        question: 'What is a Cross-Site Scripting (XSS) vulnerability primarily caused by?',
        options: [
          'Improper database indexing',
          'Rendering unsanitized user-supplied input directly in the browser DOM',
          'Using expired SSL certificates',
          'Weak server CPU specifications',
        ],
        correctAnswer: 1,
        explanation: 'XSS occurs when untrusted input is executed as script in the victim’s browser context without sanitization.',
      },
      {
        id: 7,
        question: 'What is the time complexity of searching an element in a balanced Binary Search Tree (AVL / Red-Black)?',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
        correctAnswer: 1,
        explanation: 'A balanced BST guarantees height logarithmic to number of nodes, yielding O(log n) lookup.',
      },
      {
        id: 8,
        question: 'Which Cache-Control header directive instructs browsers to validate with the server before using cached content?',
        options: ['no-store', 'no-cache', 'public, max-age=31536000', 'immutable'],
        correctAnswer: 1,
        explanation: 'no-cache allows caching but forces the browser to revalidate with the origin server before reuse.',
      },
      {
        id: 9,
        question: 'What is the purpose of React.memo() higher-order component?',
        options: [
          'To memoize heavy calculations inside a function',
          'To prevent unnecessary component re-renders if its props have not changed',
          'To cache network fetch responses in localStorage',
          'To create a global Redux store',
        ],
        correctAnswer: 1,
        explanation: 'React.memo skips rendering if previous and incoming props are shallowly equal.',
      },
      {
        id: 10,
        question: 'Which of the following is true regarding JWT (JSON Web Tokens)?',
        options: [
          'JWT payloads are encrypted by default and completely confidential without extra encryption',
          'JWT signatures verify data integrity and authenticity, but the payload is base64 encoded and readable',
          'JWTs cannot contain expiration timestamps',
          'JWTs can only be read on the server side',
        ],
        correctAnswer: 1,
        explanation: 'Standard JWS tokens are signed, not encrypted; anyone with the token can decode and inspect the claims payload.',
      },
    ],
  },
  {
    id: 2,
    title: 'Python Data Science Certification Test',
    course: 'Applied AI & Python Data Analytics',
    duration: '45 mins',
    durationMinutes: 45,
    questionsCount: 25,
    status: 'Upcoming',
    proctored: true,
    passingScore: 70,
    attemptsAllowed: 1,
    attemptsTaken: 0,
    instructions: [
      'Ensure uninterrupted high-speed internet connectivity.',
      'Proctoring will monitor tab switches and webcam presence.',
      'Results and score breakdown will be issued immediately upon submission.',
    ],
    questions: [],
  },
  {
    id: 3,
    title: 'UI/UX Design Systems Review',
    course: 'UI/UX Design Systems & Product Strategy',
    duration: '30 mins',
    durationMinutes: 30,
    questionsCount: 15,
    status: 'Completed',
    proctored: false,
    passingScore: 80,
    attemptsAllowed: 2,
    attemptsTaken: 1,
    instructions: ['Non-proctored knowledge check.'],
    questions: [],
  },
];

export const INITIAL_QUESTION_BANK: QuestionBankItem[] = [
  { id: 1, q: 'What is the primary purpose of a React component?', topic: 'React', difficulty: 'Medium', type: 'MCQ', points: 5, course: 'Full-Stack Modern Web Engineering' },
  { id: 2, q: 'Which CSS layout system is best for two-dimensional grid structures?', topic: 'CSS', difficulty: 'Easy', type: 'MCQ', points: 5, course: 'Full-Stack Modern Web Engineering' },
  { id: 3, q: 'Explain how async/await simplifies asynchronous JavaScript logic.', topic: 'JavaScript', difficulty: 'Hard', type: 'Short Answer', points: 10, course: 'Full-Stack Modern Web Engineering' },
  { id: 4, q: 'What is the main advantage of Pandas DataFrames over raw Python lists?', topic: 'Python', difficulty: 'Easy', type: 'MCQ', points: 5, course: 'Applied AI & Python Data Analytics' },
  { id: 5, q: 'Describe the difference between supervised and unsupervised machine learning.', topic: 'Machine Learning', difficulty: 'Medium', type: 'Short Answer', points: 10, course: 'Applied AI & Python Data Analytics' },
  { id: 6, q: 'How does WCAG 2.1 color contrast affect users with visual impairments?', topic: 'UI/UX', difficulty: 'Easy', type: 'MCQ', points: 5, course: 'UI/UX Design Systems & Product Strategy' },
];

export const INITIAL_STUDENTS: Student[] = [
  { id: 1, name: 'Alex Johnson', email: 'student@krytil.com', phone: '+91 98765 43210', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80', courses: 3, completion: '78%', score: '88%', status: 'Active', enrolledDate: 'Jan 15, 2026' },
  { id: 2, name: 'Priya Sharma', email: 'priya.sharma@example.com', phone: '+91 98111 22334', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80', courses: 4, completion: '91%', score: '94%', status: 'Active', enrolledDate: 'Feb 02, 2026' },
  { id: 3, name: 'Rahul Mehta', email: 'rahul.mehta@example.com', phone: '+91 98222 33445', avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80', courses: 2, completion: '64%', score: '79%', status: 'Active', enrolledDate: 'Mar 10, 2026' },
  { id: 4, name: 'Ananya Gupta', email: 'ananya.g@example.com', phone: '+91 98333 44556', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80', courses: 5, completion: '85%', score: '91%', status: 'Active', enrolledDate: 'Jan 28, 2026' },
  { id: 5, name: 'Kavita Nair', email: 'kavita.nair@example.com', phone: '+91 98444 55667', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80', courses: 1, completion: '42%', score: '74%', status: 'Inactive', enrolledDate: 'Feb 20, 2026' },
];

export const INITIAL_PAYMENTS: Payment[] = [
  { id: 'PAY-10821', studentName: 'Alex Johnson', course: 'Full-Stack Modern Web Engineering', amount: 4999, date: 'Aug 20, 2026', method: 'UPI', status: 'Paid', invoiceId: 'INV-2026-081' },
  { id: 'PAY-10820', studentName: 'Alex Johnson', course: 'UI/UX Design Systems & Product Strategy', amount: 3499, date: 'Aug 14, 2026', method: 'Credit Card', status: 'Paid', invoiceId: 'INV-2026-075' },
  { id: 'PAY-10819', studentName: 'Alex Johnson', course: 'Applied AI & Python Data Analytics', amount: 3999, date: 'Aug 05, 2026', method: 'UPI', status: 'Paid', invoiceId: 'INV-2026-062' },
  { id: 'PAY-10818', studentName: 'Priya Sharma', course: 'Data Structures, Algorithms & System Design', amount: 4299, date: 'Aug 22, 2026', method: 'Net Banking', status: 'Paid', invoiceId: 'INV-2026-084' },
  { id: 'PAY-10817', studentName: 'Rahul Mehta', course: 'Cloud Architecture & Kubernetes Orchestration', amount: 4499, date: 'Aug 21, 2026', method: 'Debit Card', status: 'Paid', invoiceId: 'INV-2026-083' },
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: 'CERT-KRY-2026-9041',
    courseId: 1,
    course: 'Full-Stack Modern Web Engineering',
    studentName: 'Alex Johnson',
    issueDate: 'Aug 15, 2026',
    credentialId: 'KRY-FSW-88492',
    instructor: 'Dr. Sarah Malik',
    grade: 'Grade A+ (Distinction)',
  },
  {
    id: 'CERT-KRY-2026-4412',
    courseId: 3,
    course: 'UI/UX Design Systems & Product Strategy',
    studentName: 'Alex Johnson',
    issueDate: 'Jul 28, 2026',
    credentialId: 'KRY-UXD-31904',
    instructor: 'Nisha Rao',
    grade: 'Grade A (Honors)',
  },
];
